name: Build and scan ROCKs, save and send scan reports

on:
  workflow_dispatch:
  #schedule:
  # every day at 1:12AM UTC
  #- cron: '12 1 * * *'
    secrets:
      JIRA_URL:
        required: true

jobs:
  build-scan-rocks:
    runs-on: ubuntu-20.04
    name: Build and scan ROCKs
    strategy:
      matrix:
        rock:
          - admission-webhook
          - centraldashboard
          - jupyter-pytorch-cuda-full
          - jupyter-pytorch-full
          - jupyter-scipy
          - jupyter-web-app
          - kfam
          - notebook-controller
          - volumes-web-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Kubeflow CI
        run: |
          CI_REPO="https://github.com/canonical/kubeflow-ci.git"
          mkdir -p kubeflow-ci
          cd kubeflow-ci
          git init -q
          git remote add -f origin "$CI_REPO" &> /dev/null
          git sparse-checkout set scripts/
          git pull -q origin main
          cd -
      - name: Install tools
        run: |
          ./kubeflow-ci/scripts/rock-build-scan/install_tools.sh
      - name: Build ROCK
        id: rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: ${{ matrix.rock }}
      - name: Copy ROCK to Docker
        run: |
          skopeo --insecure-policy copy oci-archive:${{ steps.rockcraft.outputs.rock }} \
            docker-daemon:${{ steps.rockcraft.outputs.rock }}
        working-directory: ${{ matrix.rock }}
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.rockcraft.outputs.rock }}'
          format: 'json'
          output: 'trivy-report-${{ matrix.rock }}.json'
        working-directory: ${{ matrix.rock }}
      - name: Send vulnerability records
        run: |
          ./kubeflow-ci/scripts/cve-reports/send-scan.py --report-path=${{ steps.trivy-scan.output }} \
            --jira-url=${{ secrets.JIRA_URL }}
        working-directory: ${{ matrix.rock }}
      - name: Prepare artifacts
        run: |
          tar zcvf trivy-reports-${{ matrix.rock }}.${{ strategy.job-index }}.tar.gz ./trivy-reports
        working-directory: ${{ matrix.rock }}
      - name: Upload Trivy reports
        uses: actions/upload-artifact@v3
        with:
          name: trivy-reports-${{ matrix.rock }}
          path: trivy-reports-${{ matrix.rock }}.${{ strategy.job-index }}.tar.gz

