name: Build and scan ROCKs, save and send scan reports

on:
  workflow_dispatch:
  #schedule:
  # every day at 1:12AM UTC
  #- cron: '12 1 * * *'

jobs:
  build-scan-rocks:
    name: Build and scan ROCKs
    strategy:
      matrix:
        rock:
          - centraldashboard
          - jupyter-pytorch-full
          - notebook-controller
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/build_and_scan_rock.yaml@main
    with:
      rock: ${{ matrix.rock }}
