name: CI

on:
  workflow_call:

jobs:
  build:
    name: Build rocks
    runs-on: ubuntu-22.04
    outputs:
      rockcraft-out: ${{ steps.rockcraft.outputs.rock }}
    strategy:
      matrix:
        rock:
          - admission-webhook
          - centraldashboard
          - jupyter-pytorch-cuda-full
          - jupyter-pytorch-full
          - jupyter-tensorflow-cuda-full
          - jupyter-tensorflow-full
          - jupyter-scipy
          - kfam
          - notebook-controller
          - volumes-web-app
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.24/stable
            charmcraft-channel: latest/candidate
            microk8s-addons: "dns storage rbac ingress metallb:10.64.140.43-10.64.140.49"
            juju-channel: 2.9/stable

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install tox

      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          path: ./${{ matrix.rock }}

      - name: Upload rock as artefact
        uses: actions/upload-artifact@v3
        with:
            name: kubeflow-rocks
            path: ${{ steps.rockcraft.outputs.rock }}

      - name: Unit tests
        run: tox -e unit
        working-directory: ./${{ matrix.rock }}

      - name: Integration tests
        run: |
          juju add-model kubeflow
          tox -e integration -- --model kubeflow
        working-directory: ./${{ matrix.rock }}

