name: CI

on:
  workflow_call:

jobs:
  build:
    name: Build rocks
    runs-on: ubuntu-22.04
    outputs:
      rockcraft-out: ${{ steps.rockcraft.outputs.rock }}
    strategy:
      matrix:
        rock:
          - jupyter-pytorch-cuda-full
          - jupyter-pytorch-full
          - jupyter-tensorflow-cuda-full
          - jupyter-tensorflow-full
          - jupyter-scipy
          - notebook-controller
          - volumes-web-app
    steps:
      # Ideally we'd use self-hosted runners, but this effort is still not stable.
      # This action will remove unused software (dotnet, haskell, android libs, codeql,
      # and docker images) from the GH runner, which will liberate around 60 GB of storage
      # distributed in 40GB for root and around 20 for a mnt point.
      - name: Maximise GH runner space
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 40960
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          path: ./${{ matrix.rock }}

      - name: Upload rock as artefact
        uses: actions/upload-artifact@v3
        with:
            name: kubeflow-rocks
            path: ${{ steps.rockcraft.outputs.rock }}

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
            provider: microk8s
            channel: 1.24/stable
            charmcraft-channel: latest/candidate
            microk8s-addons: "dns hostpath-storage rbac ingress metallb:10.64.140.43-10.64.140.49"
            juju-channel: 2.9/stable

      - name: Unit tests
        run: |
          tox -e integrity
        working-directory: ./${{ matrix.rock }}

      - name: Integration tests
        run: |
          tox -e integration
        working-directory: ./${{ matrix.rock }}

