name: On Pull Request

# On pull_request, we:
# * always build the rocks
# * always run tests

on:
  pull_request:

jobs:

  tests:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        path: 'jupyter-scipy'
        fetch-depth: 0

    - name: Run Tests
      uses: ./.github/workflows/integrate.yaml
      with:
        rock: 'jupyter-scipy'
