name: On Pull Request

# On pull_request, we:
# * always build the rocks
# * always run tests

on:
  pull_request:

jobs:

  tests:
    name: Run Tests
    strategy:
      matrix:
        rock:
          - jupyter-pytorch-cuda-full
          - jupyter-pytorch-full
          - jupyter-tensorflow-cuda-full
          - jupyter-tensorflow-full
          - jupyter-scipy
          - notebook-controller
          - volumes-web-app

    uses: ./.github/workflows/integrate.yaml
    with:
      rock: ${{ matrix.rock }}
